### ISSUE TITLE
Tìm hiểu phương thức bảo mật cho trang web, sử dụng mã hóa

### ISSUE THREAD

**Issue by trnguyen199** [trnguyen199/Diamond-Shop#10]
Tìm hiểu phương thức bảo mật cho trang web, sử dụng mã hóa như thế nào là hợp lí (Ví dụ: mã hóa mật khẩu người dùng, mã hóa địa chỉ, ...)
Yêu cầu: Thông tin về các phương thức bảo mật, ưu và nhược điểm của nó. Thực hành thử với một số phương thức bảo mật đó với trang web mẫu. Nộp file docs và code

**Comment by tailuvem** [comment]
[ma hoa.docx](https://github.com/user-attachments/files/18167990/ma.hoa.docx)

**Comment by tailuvem** [comment]
code nộp ở phần code
