### ISSUE TITLE
Thiết kế giao diện cho trang đăng nhập/đăng ký

### ISSUE THREAD

**Issue by trnguyen199** [trnguyen199/Diamond-Shop#11]
Yêu cầu: Cần có thông tin thể hiện đó là trang web bán kim cương như câu slogan (Uy tính, chất lượng; Kim cương tự nhiên; ...) và phần đăng nhập/đăng ký. Nộp hình ảnh và file code (html, css)
mẫu https://imta.edu.vn/wp-content/uploads/2021/07/doi-duong-dan-url-trang-dang-nhap-wordpress-scaled.jpg

**Comment by Binhnealo** [comment]
![Image](https://github.com/user-attachments/assets/14ef2c0d-c15d-4329-91d7-6e95ac5e5efd)
complete sign in

**Comment by Binhnealo** [comment]
![Image](https://github.com/user-attachments/assets/a2b7e218-e4c4-4476-8c6c-881f4457464d)
completed sign up
