### ISSUE TITLE
Quản lý người dùng

### ISSUE THREAD

**Issue by trnguyen199** [trnguyen199/Diamond-Shop#13]
Tìm hiểu và thiết lập các hàm dưới đây để đồng bộ với website
Đăng ký người dùng (register_user): Thêm người dùng mới.
Đăng nhập người dùng (login_user): Kiểm tra thông tin đăng nhập.
Đăng xuất người dùng (logout_user): Xóa phiên người dùng.
Quản lý vai trò (manage_roles): Phân quyền (admin, nhân viên, khách hàng).

**Comment by ThangLC2209** [comment]
![image](https://github.com/user-attachments/assets/06210127-69f8-4a46-b37a-3ec60accea75)

**Comment by ThangLC2209** [comment]
![Uploading image.png…]()

**Comment by ThangLC2209** [comment]
![Uploading image.png…]()

**Comment by ThangLC2209** [comment]
![Uploading Screenshot 2024-12-28 214548.png…]()

**Comment by ThangLC2209** [comment]
![Screenshot 2024-12-28 214811](https://github.com/user-attachments/assets/3c3dda39-1beb-409c-ae43-46ebecb821a8)

**Comment by ThangLC2209** [comment]
![Screenshot 2024-12-28 214950](https://github.com/user-attachments/assets/e9ca60bb-4491-4a69-a557-a0ce6d1358ff)

**Comment by ThangLC2209** [comment]
[Diamond-shop.zip](https://github.com/user-attachments/files/18266518/Diamond-shop.zip)

**Comment by ThangLC2209** [comment]
![Image](https://github.com/user-attachments/assets/cd5bdbb0-684a-4855-8002-44a23117c723)

**Comment by ThangLC2209** [comment]
![Image](https://github.com/user-attachments/assets/a70f47f1-506b-43b0-bfba-748888129f22)
