### ISSUE TITLE
Chương trình khuyến mãi, tích lũy điểm khi mua

### ISSUE THREAD

**Issue by trnguyen199** [trnguyen199/Diamond-Shop#2]
Khi khách hàng mua sẽ khuyến mãi theo số lần mua, hoặc hóa đơn trên số tiền đã được định sẵn, và tích lũy điểm tăng dần theo giá trị của hóa đơn.
Hãy lập ra một bảng khuyến mãi và tích lũy điểm cho khách hàng

**Comment by ThangLC2209** [comment]
[Bảng khuyến mãi-ThangLC2209.xlsx](https://github.com/user-attachments/files/18091529/B.ng.khuy.n.mai-ThangLC2209.xlsx)
