### ISSUE TITLE
Nội dung cho website (Tab1)

### ISSUE THREAD

**Issue by trnguyen199** [trnguyen199/Diamond-Shop#3]
Giới thiệu: Giới thiệu cửa hàng, sản phẩm, bộ sưu tập, bảng giá, kiến thức về trang sức, hướng dẫn chọn ni, và các câu hỏi thường gặp. Yêu cầu: Nộp file word chứa nội dung phần giới thiệu trên, các nội dung cần thiết ngắn gọn.

**Comment by trnguyen199** [comment]
nộp file lên phần comment nha

**Comment by TrieuPhu22** [comment]
[Uploading Nội dung cho webside(tab 1).docx…]()
