### ISSUE TITLE
Bảng giá kim cương hiện tại

### ISSUE THREAD

**Issue by trnguyen199** [trnguyen199/Diamond-Shop#4]
Khai báo bảng giá viên kim cương theo các tiêu chí: loại nguồn gốc (diamond origin), trọng lượng (Carat weight), màu sắc (Color), độ tinh khiết (Clarity), cắt mài (Cut); khai báo bảng giá vỏ kim cương.
Tìm hiểu và thiết kế bảng giá kim cương theo các tiêu trí trên 
 <<Giá bán = giá vốn sản phẩm * tỉ lệ áp giá, Giá vốn sản phẩm = tiền kim cương + vỏ kim cương + tiền công>>

**Comment by Kietnormal** [comment]
[DIAMOND_PRICE BY KIETNORMAL.xlsx](https://github.com/user-attachments/files/18091546/DIAMOND_PRICE.BY.KIETNORMAL.xlsx)

**Comment by Kietnormal** [comment]
[DIAMOND_PRICE BY KIETNORMAL.xlsx](https://github.com/user-attachments/files/18095914/DIAMOND_PRICE.BY.KIETNORMAL.xlsx)
 bản final
