### ISSUE TITLE
Ý tưởng thiết kế giao diện website

### ISSUE THREAD

**Issue by trnguyen199** [trnguyen199/Diamond-Shop#5]
Giao diện website: 
- Tên cửa hàng 
- Giới thiệu
- Danh mục (Cần những danh mục gì?): trong danh mục gồm có các danh mục con theo các cấp
- Giỏ hàng
- Đăng ký/ đăng nhập tài khoản cho user
- ...
Có thể tạo thử bằng html hoặc vẽ ra ý tưởng cho trang web

**Comment by Binhnealo** [comment]
https://www.figma.com/design/RkUIe30uOHrNIEum3CGxNy/design?node-id=0-1&node-type=canvas&t=pzNtSDNmyWXG4xL9-0

**Comment by Binhnealo** [comment]
link figna https://www.figma.com/design/RkUIe30uOHrNIEum3CGxNy/design?node-id=0-1&node-type=canvas&t=pzNtSDNmyWXG4xL9-0
