### ISSUE TITLE
Tìm kiếm sản phẩm

### ISSUE THREAD

**Issue by trnguyen199** [trnguyen199/Diamond-Shop#6]
Tìm kiếm tên, ảnh sản phẩm up lên drive 
lưu tên file theo mẫu: 
bong-tai-kim-cuong-1001.jpg
bong-tai-kim-cuong-1002.jpg
nhan-kim-cuong-2001.jpg
...
Và 1 file excel để lưu thông tin từng sản phẩm
Thiết kế các bảng theo dạng cột với những thông tin mẫu đã cho
**Ví dụ:** 
Bông tai: 1 , nhẫn: 2, dây chuyền: 3, ...
Mã sản phẩm ghép từ mã danh mục sản phẩm + 001 (tăng dần theo số lượng)

**Table danh mục:**
Tên danh mục sản phẩm      Bông tai kim cương 
Mã danh mục sản phẩm      1

**Table sản phẩm**
Tên sản phẩm                                      Mã sản phẩm               Mã danh mục sản phẩm     Thông tin sản phẩm
                                                                                                                                             Kiểu dáng  |   Chất liệu
Bông xoàn kim cương Geogria               1001                                         1                             ....              kc thiên nhiên

**Comment by RMYiii** [comment]
[Task Of GHuy.xlsx](https://github.com/user-attachments/files/18095522/Task.Of.GHuy.xlsx)

**Comment by trnguyen199** [comment]
chưa thấy phần hình ảnh á

**Comment by RMYiii** [comment]
Phần ảnh tui gửi trong zalo á - Gửi thư mục nó load từng ảnh á

**Comment by RMYiii** [comment]
Giờ tui mới check tin sorry

**Comment by RMYiii** [comment]
[Diamond Shop Online.xlsx](https://github.com/user-attachments/files/18200436/Diamond.Shop.Online.xlsx)
![Image](https://github.com/user-attachments/assets/32e708d9-e352-499e-9a38-e71fe32885a8)
![Image](https://github.com/user-attachments/assets/2c32e0e0-00db-4c03-aecd-1e67dae8b6c6)
![Image](https://github.com/user-attachments/assets/3593794d-5d28-42a6-a228-4da2c13efe3c)
![Image](https://github.com/user-attachments/assets/06375239-dc7a-4ba6-8942-54a414c10222)
![Image](https://github.com/user-attachments/assets/2856efbd-18ae-4254-a7cd-7059e7f5d5cd)
![Image](https://github.com/user-attachments/assets/7b5f360b-ba0b-4e69-bbf6-f82b744f662e)
![Image](https://github.com/user-attachments/assets/41d49d8e-4b9e-4777-99a0-58549b4f64ec)
![Image](https://github.com/user-attachments/assets/31d7c95e-a7a7-4db7-be69-f858477e01f6)
![Image](https://github.com/user-attachments/assets/b0e83aab-6b02-472c-a172-0e57b2c44b74)
![Image](https://github.com/user-attachments/assets/79e1b3f8-90a4-44cc-bc29-cd614357abfc)
![Image](https://github.com/user-attachments/assets/1bca5308-741a-4e6e-9191-2400df864a9f)
![Image](https://github.com/user-attachments/assets/bd57b7a7-3ca4-42cd-a956-d7afb45e585c)
