### ISSUE TITLE
Chuẩn bị phần cơ sở dữ liệu (Backend)

### ISSUE THREAD

**Issue by trnguyen199** [trnguyen199/Diamond-Shop#7]
HÃY TÌM NHỮNG BẢNG CẦN THIẾT CHO WEBSITE:
- Bảng products (id, name, price, description, image). 
- Bảng users (id, email, password, role). 
- Bảng orders (id, user_id, product_id, quantity, total_price, status).
- ...
ví dụ: tin tức, bảng tin, news,...
*** Mỗi thành viên sẽ đóng góp ít nhất 1 table, comment vào task này (Lưu ý: Các bảng phải cần thiết với dự án này)

**Comment by ThangLC2209** [comment]
![Image](https://github.com/user-attachments/assets/edfd5552-f563-4092-87a1-5dd7e24e0859)

**Comment by Kietnormal** [comment]
![Image](https://github.com/user-attachments/assets/da0d6cc4-9056-449b-84ba-0a545fe095a9)

**Comment by RMYiii** [comment]
![Image](https://github.com/user-attachments/assets/a4b9f3c5-8cbd-4127-853b-0ba87d8ed65b)

**Comment by TrieuPhu22** [comment]
![Image](https://github.com/user-attachments/assets/3c292d33-8500-4081-b065-a4e9d78968b7)
