### ISSUE TITLE
Thiết kế cơ sở dữ liệu bằng sql và connect với website

### ISSUE THREAD

**Issue by trnguyen199** [trnguyen199/Diamond-Shop#8]
Lấy từ table từ task "Chuẩn bị cơ sở dữ liệu (Backend)" 
- Thử kết nối cơ sở dữ liệu đó bằng python với một website 
Yêu cầu: Nộp hình ảnh và code (python)

mẫu (  ![Image](https://github.com/user-attachments/assets/3e5cfebe-4ea5-4da2-b1b0-2551d255a887) ) 
![Image](https://github.com/user-attachments/assets/ffb7df2d-4e1e-42e7-8191-8e6d3bdc72fa)

**Comment by ThangLC2209** [comment]
![Image](https://github.com/user-attachments/assets/1072b655-4b13-4c01-bc16-ad052edf2939)

**Comment by ThangLC2209** [comment]
![Image](https://github.com/user-attachments/assets/cd7fbb9f-1375-4e63-a7bf-51196d4acd5c)

**Comment by ThangLC2209** [comment]
import mysql.connector

try:
    # Kết nối đến MySQL và chỉ định database 'qlkc'
    db = mysql.connector.connect(
        user='root',
        password='Thang2209*',
        host='localhost',
        database='qlkc'  # Đúng tham số
    )

    # Tạo con trỏ để thao tác với MySQL
    mycursor = db.cursor()

    # Lệnh SQL ví dụ
    code = "SHOW TABLES;"  # Hoặc một câu lệnh khác bạn muốn chạy
    mycursor.execute(code)

    # Lấy kết quả và in ra
    print("Các bảng trong cơ sở dữ liệu 'qlkc':")
    for table in mycursor:
        print(table)

except mysql.connector.Error as e:
    print(f"Lỗi khi kết nối hoặc truy vấn MySQL: {e}")

finally:
    if db.is_connected():
        mycursor.close()
        db.close()
        print("Đã đóng kết nối đến MySQL.")

**Comment by TrieuPhu22** [comment]
import mysql.connector

try:
# Kết nối đến MySQL và chỉ định database 'qlkc'
db = mysql.connector.connect(
user='root',
password='Phu0011223',
host='localhost',
database='qlkc'
)

# Tạo con trỏ để thao tác với MySQL
mycursor = db.cursor()

# Lệnh SQL ví dụ
code = "SHOW TABLES;"  # Hoặc một câu lệnh khác bạn muốn chạy
mycursor.execute(code)

# Lấy kết quả và in ra
print("Các bảng trong cơ sở dữ liệu 'qlkc':")
for table in mycursor:
    print(table)
except mysql.connector.Error as e:
print(f"Lỗi khi kết nối hoặc truy vấn MySQL: {e}")

finally:
if db.is_connected():
mycursor.close()
db.close()
print("Đã đóng kết nối đến MySQL.")
